### ISSUE TITLE
Intermittent Threading Hang

### ISSUE THREAD

**Issue by ztgrace** [ztgrace/changeme#22]
Occasionally the app completes processing but fails to exit the program cleanly. Need to investigate and fix this.

**Comment by edoz90** [comment]
A similar problem is present when hitting Ctrl+C during the execution: program recieve the keyboard interrupt but fails to completly quit.

**Comment by ztgrace** [comment]
@edoz90 yes, I've run into this as well. For now, you can type `ctrl+z` to stop the process and then `kill %%` to terminate the process.
