### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by agc93** [ztgrace/changeme#34]
It looks like the Dockerfile is broken again. Output of `docker build -t changeme .` from latest `master` doesn't build:

```
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2k-r0:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2k]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2k]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2k]
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2k-r0[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2k-r0[pc:libssl=2.4.4]
               openssl-dev-1.0.2k-r0[pc:openssl=2.4.4]
    satisfies:
               postgresql-dev-9.6.2-r0[libressl-dev]
  .build-deps-0:
    masked in: cache
    satisfies: world[.build-deps]
```

Looks like one of the new dependencies from 2df3b3181453c02f2a128211d4f2826d9c6b74c7 has brought in `libressl-dev` which conflicts with `openssl-dev`.

Removing `openssl-dev` from the deps list seems to work again. I'll raise a PR as soon as I get a chance.

**Comment by ztgrace** [comment]
Thanks for letting me know about the issue. I fixed up the Dockerfile and integrated the build with Docker Hub.

Updated instructions are in the [README](https://github.com/ztgrace/changeme/blob/master/README.md) but now you can `docker pull ztgrace/changeme` to grab the latest and go.

Cheers,
Zach

**Comment by agc93** [comment]
Awesome, thanks @ztgrace !
