### ISSUE TITLE
No Module named redis

### ISSUE THREAD

**Issue by turnerdb** [ztgrace/changeme#41]
Cloned and move to a working directory.  Attempting to run from the local machine rather than from a docker container.  My coding/scripting skills are not excellent.  Receiving the following:

Traceback (most recent call last):
  File "./changeme.py", line 3, in <module>
    from changeme import core
  File "/opt/ChangeMe/changeme/core.py", line 3, in <module>
    from changeme.redis_queue import RedisQueue
  File "/opt/ChangeMe/changeme/redis_queue.py", line 1, in <module>
    import redis
ImportError: No module named redis

**Comment by ztgrace** [comment]
Please install the requirements according to the installation instructions: https://github.com/ztgrace/changeme#installation

**Comment by turnerdb** [comment]
My fault.  I misread.  I thought you the system used sqllite and you only needed to install unixodbc-dev if you wanted to use mssql.  Works fine now.   Thank you!  I can't wait to work with this.  We were using EyeWitness are were beyond frustrated with the amount of false positives.

**Comment by turnerdb** [comment]
Getting the sqlite3.OperationError.  But I see a solution for that one already.  Not sure how to tell changeme to use a local redis server though.  Point me in the right direction if you can.  Thanks.
