### ISSUE TITLE
Name field within cch.yml is incorrect (conflicts with MSSQL)

### ISSUE THREAD

**Issue by UrfinJusse** [ztgrace/changeme#62]
Name field within cch.yml file incorrectly states "MSSQL" and conflicts with mssql.yml. Changing name field within cch.yml to "CCH" fixes the issue.

**Comment by ztgrace** [comment]
Thanks for the bug report. Feel free to make a pull request to the development branch if you have time. Otherwise I'll include it with the next release.

**Comment by ztgrace** [comment]
Should be fixed with release v1.1.
