### ISSUE TITLE
AttributeError: 'module' object has no attribute 'banner'

### ISSUE THREAD

**Issue by LordWeeble** [ztgrace/changeme#63]
root@kali:~/githubtools/changeme# ./changeme.py -s 10.217.24.0/24
Traceback (most recent call last):
  File "./changeme.py", line 47, in <module>
    print core.banner(version.__version__)
AttributeError: 'module' object has no attribute 'banner'

**Comment by ztgrace** [comment]
Thanks for the report, what version of changeme do you have and how was it installed (kali, git, etc)?

**Comment by LordWeeble** [comment]
You can close this they added changme to the Kali rolling distro and I dont have issues anymore when creating a new VM.

**Comment by ztgrace** [comment]
It looks like Kali is really far behind in the version based on: https://pkg.kali.org/pkg/changeme. I'd recommend pulling down the [latest release](https://github.com/ztgrace/changeme/releases) and following the [installation instructions](https://github.com/ztgrace/changeme#installation).
