### ISSUE TITLE
Error when run chageme

### ISSUE THREAD

**Issue by tatdat171** [ztgrace/changeme#7]
I try to run changeme with command
`./changeme.py -s x.x.x.x`

And got error
```
Traceback (most recent call last):
  File "./changeme.py", line 4, in <module>
    import requests
ImportError: No module named requests
```
I try to list all module and i saw module reuqest is installed 

### pip3 list
```
Cerberus (0.9.2)
cookies (2.2.1)
dnspython3 (1.12.0)
intelmq (1.0.0.dev4)
logutils (0.3.3)
lxml (3.6.0)
netaddr (0.7.18)
nose (1.3.7)
pip (8.1.1)
psutil (4.1.0)
pycurl (7.43.0)
python-dateutil (2.5.3)
python-termstyle (0.1.10)
pytz (2016.4)
PyYAML (3.11)
redis (2.10.5)
requests (2.9.1)
responses (0.5.1)
setuptools (20.10.1)
six (1.10.0)
wheel (0.29.0)
```

**Comment by ztgrace** [comment]
It doesn't look like the requests library is installed. What OS are you using?

Also, can you paste the output of these two commands?

`sudo pip install -r requirements.txt`

`python -c 'import requests'`

**Comment by ztgrace** [comment]
No response in 7 days, closing.
