### ISSUE TITLE
Error Cannot Allocate Memory

### ISSUE THREAD

**Issue by sdcampbell** [ztgrace/changeme#76]
```
Traceback (most recent call last):
  File "./changeme.py", line 6, in <module>
    core.main()
  File "/root/sc/tools/changeme/changeme/core.py", line 69, in main
    s.scan()
  File "/root/sc/tools/changeme/changeme/scan_engine.py", line 59, in scan
    proc.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
I checked free memory and this is what I found:

```
# free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       1.4Gi       6.3Gi       8.0Mi       160Mi       6.2Gi
Swap:         2.0Gi       733Mi       1.3Gi
```
There seems to be plenty of memory available. I ran this on two different systems (both were Kali Linux virtual machines) and got the same error on both.

**Comment by sdcampbell** [comment]
I also noticed that this happens when I specify a file with a list of /24 networks to scan. It didn't fail when I scanned a single host.

**Comment by ztgrace** [comment]
Thanks for the report, I haven't heard of this issue happening before. Could you please pass along the command line arguments you used?

**Comment by ztgrace** [comment]
Not sure if you're still having this issue, but I haven't been able to reproduce it nor have I had any other reports. If the issue persists for you, we can re-open this issue for further troubleshooting.
