### ISSUE TITLE
ImportError: No module named cerberus

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [ztgrace/changeme#94]
Thank you for making this tool. But, I'm having real issues with installing it. I followed the instructions line by line in Kali Linux. But, I cannot get this this to work. I have the below error:

Traceback (most recent call last):
  File "changeme.py", line 3, in <module>
    from changeme import core
  File "/usr/share/changeme/changeme/core.py", line 2, in <module>
    from cerberus import Validator
ImportError: cannot import name 'Validator' from 'cerberus' (/usr/local/lib/python3.8/dist-packages/cerberus/__init__.py)

I did what I could to debug it. I've installed, removed, and reinstalled multiple times. The only thing that I can really see is that someone had an issue, and never followed up: https://github.com/ztgrace/changeme/issues/92

Can you please help me understand what the issue could be? Thank you so much for your time.

**Comment by ztgrace** [comment]
If you're in Kali, the latest stable release is available via `apt install changeme`: https://pkg.kali.org/news/374202/changeme-121-1-imported-into-kali-rolling/

If you're looking to install it manually, try using a python virtual environment.

```
$ virtualenv -p /usr/bin/python3 venv
$ source venv/bin/activate
$ venv/bin/pip3 install -r requirements.txt
```

If either of these options don't work, please post the output of `venv/bin/pip3 freeze` here.

**Comment by BetaMaxHeadroom** [comment]
Thank you for your help. I really appreciate it. 

I still get the same error when installing this via apt. I will look into installing it in a virtual environment. Thank you for your help.

**Comment by BetaMaxHeadroom** [comment]
Installing this in a virtual environment seems to have done the trick. Thank you for being so awesome.
